### ISSUE TITLE
Invalid encoding of compression info parameter

### ISSUE THREAD

**Issue by mjurczak** [suit-wg/manifest-spec#19]
In **draft-ietf-suit-manifest-04**
_[12.5.  Example 4: Load and Decompress from External Storage](https://github.com/suit-wg/manifest-spec/blob/ebf7e0d635938ba467937ed78a1bdd867bc32aa5/draft-ietf-suit-manifest.txt#L3446)_
The encoding of compression info parameter does not follow the specification. The example manifest encodes compression-info as a single integer. Specification provides the following encoding rules:
```
  SUIT_Parameters //= (suit-parameter-compression-info
      => bstr .cbor SUIT_Compression_Info)
  SUIT_Compression_Info = {
      suit-compression-algorithm => SUIT_Compression_Algorithms,
      ? suit-compression-parameters => bstr
  }
```

Load sequence from the example 04:

88       # array(8)
   0C    # unsigned(12)
   01    # unsigned(1)
   13    # unsigned(19)
   A2    # map(2)
      **13 # unsigned(19)
      01 # unsigned(1)**
      16 # unsigned(22)
      00 # unsigned(0)
   16    # unsigned(22)
   F6    # primitive(22)
   03    # unsigned(3)
   F6    # primitive(22)

**Comment by bremoran** [comment]
The latest examples no longer exhibit this error.
