### ISSUE TITLE
Image digest calculation

### ISSUE THREAD

**Issue by mjurczak** [suit-wg/manifest-spec#21]
In 12.5.  Example 4: Load and Decompress from External Storage
and in some of other examples _condition-image-match_ is used in several sequences. 

The condition is specified in the following way:
https://github.com/suit-wg/manifest-spec/blob/ebf7e0d635938ba467937ed78a1bdd867bc32aa5/draft-ietf-suit-manifest.txt#L1836-L1842

Then image digest condition is checked in install, validate and load sequences:
https://github.com/suit-wg/manifest-spec/blob/ebf7e0d635938ba467937ed78a1bdd867bc32aa5/draft-ietf-suit-manifest.txt#L3511-L3532

The load sequence suggests that the image was fetched in compressed form and it may be uncopressed when executing copy directive. It is not clear if the digest provided for the component is the digest before update (current state - e.g. to verify the version of currently loaded software), is it the digest of fetched image (gziped package) or is it the digest after unpacking and executing copy directive?

**Comment by bremoran** [comment]
@mjurczak The image digest check is evaluated at the current state of the image, whatever that means. It is a deliberately naïve implementation. In example 4, the image is downloaded (but not decompressed) and thus retains its compressed image digest. Next, it is "installed" to the external memory. It is not decompressed, so it retains the same image digest. However, the manifest does not specify a way to express this information, so the digest is duplicated. Finally, it is loaded and decompressed. This digest will be different and it is expressed in the "load" parameters.

This should be clearer in the latest versions of the examples.
