### ISSUE TITLE
Automatic validation for examples

### ISSUE THREAD

**Issue by kaduk** [suit-wg/manifest-spec#28]
As we get into later stages of publication (both for this document and for other documents providing example SUIT manifests), it will be useful to have some tooling to validate that the examples in the document are valid examples of the current protocol syntax.  This may be as "simple" as just confirming that they conform to the CDDL, but having some kind of scripted validation would be nice to have.

**Comment by oyvindronningstad** [comment]
I'm able to validate using https://github.com/NordicSemiconductor/cddl-gen. One of the test cases for the project uses the examples from manifest12: https://github.com/NordicSemiconductor/cddl-gen/tree/master/tests/scripts
