### ISSUE TITLE
Hackathon114: SUIT_Parameters should be a socket

### ISSUE THREAD

**Issue by dthaler** [suit-wg/manifest-spec#66]
SUIT_Parameters should be $$SUIT_Parameters throughout.

Without the $$ it means that the definition in the SUIT manifest spec is a closed set and cannot be extended without rev'ing the document.  But other documents such as draft-ietf-suit-update-management do extend it by adding additional parameters.  This is only legal if $$ is used to make it be an extensible socket.

The $$ also must appear anywhere SUIT_Parameters is used, including in draft-ietf-suit-update-management and draft-ietf-suit-report.

SUIT_Directive should probably be a socket as well given the manifest spec says: "The byte code can be extended by registering new operations."
"

**Comment by mcd500** [comment]
Related https://github.com/suit-wg/manifest-spec/issues/65
