### ISSUE TITLE
Hackathon114: Key label 7 is conflicted

### ISSUE THREAD

**Issue by kentakayama** [suit-wg/manifest-spec#70]
Recently the key labels are changed,
and now it defines `suit-validate = 7` (see https://github.com/suit-wg/manifest-spec/blob/master/draft-ietf-suit-manifest.cddl#L213).
However, the label value `7` was originally used by `suit-dependency-resolution = 7` and now it is located in the Multiple Trust Domains document (see https://datatracker.ietf.org/doc/html/draft-ietf-suit-trust-domains-00#appendix-A).

@bremoran 
How about updating the Multiple Trust Domains document like below.
```
- suit-dependency-resolution = 7
+ suit-dependency-resolution = 15
```
If there is a github repo that hosts the document, I will send a Pull Request to it.

**Comment by bremoran** [comment]
Exactly, that's what it should be. That was missed unfortunately.

**Comment by bremoran** [comment]
https://github.com/bremoran/suit-multiple-trust-domains

**Comment by kentakayama** [comment]
Thanks!

**Comment by kentakayama** [comment]
I've changed my mind because you know the appropriate value to be assigned.
Do it on your side, please.
